name: video-ir
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - jupyter
  - jupyterlab[version='>=3.0.0,<4.0.0a0']
  - matplotlib
  - transformers
  - datasets
