name: video-ir
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - jupyter
  - jupyterlab[version='>=3.0.0,<4.0.0a0']
  - matplotlib
  - transformers
  - datasets
  - pip:
      - imageio
      - pytube
      - decord
      - git+https://github.com/soCzech/TransNetV2.git@85cef72af9a916bdfd7cc94a670c9cdfbf12d1ed
